version: '3.8'

services:
  apache-server:
    image: httpd:2.4-alpine
    container_name: apache_server
    volumes:
      - ./public-html:/usr/local/apache2/htdocs/
    networks:
      - rede-projeto

  nginx-proxy:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - apache-server
    networks:
      - rede-projeto

networks:
  rede-projeto:
    driver: bridge